# Continuous integration (CI) triggers cause a pipeline to run whenever you push 
# an update to the specified branches or you push specified tags.
trigger:
  branches:
    include:
    - main

# Opt out of pull request validation 
pr: none

# By default, use self-hosted agents
pool: Default

resources:
  repositories:
  # Azure DevOps repository
  - repository: imagestream-quay-test-pipelines
    type: git
    # project/repository
    name: imagestream-quay-test/imagestream-quay-test-pipelines

extends:
  template: azure-pipelines-imagestream-quay-test-ui-devtest.yml@imagestream-quay-test-pipelines
